### ISSUE TITLE
Weird glosses in the annotation of phoenix dataset

### ISSUE THREAD

**Issue by sunke123** [ycmin95/VAC_CSLR#13]
Hi @ycmin95 , recently, I checked the annotation of phoenix dataset and the gloss dictionary generated during the progress of data preparation.
There are many weird glosses, such as "__ON__", "__OFF__", "__LEFTHAND__" ...
![image](https://user-images.githubusercontent.com/11239351/165294945-3730d5d2-23fd-4d2d-864a-292ca6bfd14e.png)
I wonder whether we should keep these weird glosses in the label...
Any advice?

**Comment by ycmin95** [comment]
Hi, if you look the evaluation script, you will find that most stop words and synonyms are filtered or merged, which can be found [here](https://raw.githubusercontent.com/ycmin95/VAC_CSLR/main/evaluation/slr_eval/preprocess.sh). And this script is modified from the original evaluation script provided in PHOENIX14 (./phoenix-2014-multisigner/evaluation/evaluatePhoenix2014.sh).
The left "weired glosses" are ON and OFF, from my understanding, they means pause of sentence, which is also useful for understanding. And the recognition results on these two glosses are acceptable, so I keep the same evaluation method as the dataset provided.

**Comment by sunke123** [comment]
Got it~ Thanks~
