### ISSUE TITLE
ctcdecode does not support windows, is there any other decoder alternative

### ISSUE THREAD

**Issue by HW140701** [ycmin95/VAC_CSLR#19]
ctcdecode does not support windows, is there any other library that can be used instead?

**Comment by ycmin95** [comment]
All experiments are conducted based on Ubuntu 18.04 system, I have not try it on windows. You can find some python versions which may be suitable for windows.

**Comment by HW140701** [comment]
Thanks for your reply.
I found some python versions of ctcdecode, like

1. [https://github.com/kensho-technologies/pyctcdecode](https://github.com/kensho-technologies/pyctcdecode)
2. [https://github.com/githubharald/CTCDecoder](https://github.com/githubharald/CTCDecoder)

I will do a replacement test.

**Comment by ycmin95** [comment]
Compared merge both windows and ubuntu into the same repo, it may be better to maintain them in two independent repos. You can develop windows version in your fork, and I will update Readme.md and refer to it after you finish the windows version.

**Comment by HW140701** [comment]
I'll try, and if it works and the verification results are no wrong, I'll make a pull request.

**Comment by xuqico** [comment]
> 我会尝试，如果它有效并且验证结果没有错误，我会提出拉取请求。

Hello is there a solution for installing CTCdecode using windows yet?
