### ISSUE TITLE
Finetuning and continue training

### ISSUE THREAD

**Issue by khoapip** [ycmin95/VAC_CSLR#23]
Hello, Thank you for the awesome work. I am trying to use the model on another dataset, so I figure I should structure my data accordingly to the format of phoenix2014. Is there anything else I should worry about or just running the preprocessing with the same structure is gonna be alright?

Also, since I am training on google colab, I won't be able to train for 80 epochs consecutively and plan to split it into several different runs. Is there a built in function to load the previous model and continue training (or finetuning, if I want to finetune the pretrain) or how should I begin to tackle this problem? I am not sure if --load-weights tag is enough. Thank you so much.

**Comment by ycmin95** [comment]
Thanks for your attention, If your resolusion of video data is pretty high, perhaps a human detection can preserve more useful information before resizing the whole image. Our recent version can achieve comparable results with 40 epochs, and --load-checkpoints can load the previous model and continue training. Details can be found in [config](https://github.com/ycmin95/VAC_CSLR/blob/main/utils/parameters.py#L100) and [here](https://github.com/ycmin95/VAC_CSLR/blob/main/main.py#L141).

Good luck~
