### ISSUE TITLE
Request for experiment dataset phoenix-2014.v3.tar.gz.

### ISSUE THREAD

**Issue by Claire874** [ycmin95/VAC_CSLR#27]
Hi
Thanks for your great work in Sign language recognition.
The download link seems expire, would you mind sharing the dataset you used below?

**Comment by ycmin95** [comment]
Hi, thanks for your attention to this work. We do not have the permission to share this dataset. You can try to contact authors of this dataset, which can found in related publications:

O. Koller, J. Forster, and H. Ney. Continuous sign language recognition: Towards large vocabulary statistical recognition systems handling multiple signers. Computer Vision and Image Understanding, volume 141, pages 108-125, December 2015.
O. Koller, S. Zargaran, and H. Ney. "Re-Sign: Re-Aligned End-to-End Sequence Modeling with Deep Recurrent CNN-HMMs" in CVPR 2017, Honululu, Hawaii, USA.

**Comment by ycmin95** [comment]
It seems that the download link has recovered~

**Comment by Claire874** [comment]
thanks I got the dataset
