### ISSUE TITLE
Data augmention error

### ISSUE THREAD

**Issue by btt-creator** [ycmin95/VAC_CSLR#35]
Hi,author! I'm doing a data augmentation task，and I get problems every time I run to batch 777(The training set is twice as large as before)。I've seen your previous answer about "Index error:list out of range" but I have detected that the frame path is correct。（by the way batch_size is 4,device is 4）
![image](https://user-images.githubusercontent.com/92516701/233837029-ae17e2e1-4b13-4b12-a179-99dfb7ae1cb9.png)

**Comment by ycmin95** [comment]
Hi @tanbitao, you can try to capture this index error and provide more details about this error.

**Comment by btt-creator** [comment]
thank you，author！i‘ve solved this question!

**Comment by btt-creator** [comment]
thank you！i’ve solved this question!Have a good day!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ycmin95/VAC_CSLR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月23日(星期天) 晚上9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ycmin95/VAC_CSLR] Data augmention error (Issue #35)





 
Hi @tanbitao, you can try to capture this index error and provide more details about this error.

**Comment by WhiteButterflies** [comment]
The csv file have a broken data.In the vac code,the author had deleted it.when we change the csv file,we should delete anthoner data.
做数据增强时，将csv文件扩充了两倍，但是之前的csv文件里面2390这个数据是坏的，当我们扩充时，需要将对应2390的那条数据也做drop处理。
