### ISSUE TITLE
about the feature extractor architecture

### ISSUE THREAD

**Issue by fransisca25** [ycmin95/VAC_CSLR#36]
Hi, I am really sorry to ask question here, but this is something important for my research. I really want to know more about the delta t from the frame wise features. There are intersections between the delta ts. Could you explain how long are the intersections between those delta ts? Or maybe you could mention the code about the delta t, so I can check it? Thank you.
![Screenshot from 2023-05-08 14-49-30](https://user-images.githubusercontent.com/102350090/236745054-da1b58ae-0d84-47f5-b441-caf0e96dedd8.png)

**Comment by ycmin95** [comment]
Hi, thanks for your attention to our work and please feel free to post any question here,
the delta t here is implemented by conv1d on the temporal dimention with stride=1, and the implementation can be found [here](https://github.com/ycmin95/VAC_CSLR/blob/main/modules/tconv.py#L18). The ablation results about the length of delta t can be found in the Table 4 of the main paper.

Hope can help you~

**Comment by fransisca25** [comment]
This really helps me. Thank you so much for answering my question!

**Comment by atonyo11** [comment]
Hi @ycmin95 , @fransisca25, can you explain how to calculate the delta t? For example C5-P2-C5-P2? Thank you in advance!

**Comment by ycmin95** [comment]
Hi @atonyo11 ,
The equation for the receptive field calculation is RF_i = (RF_i-1) * stride + Ksize

For C5-P2-C5-P2:

-P2: (1-1)*2+2=2
-C5-P2: (2-1)*1+5=6
-P2-C5-P2: (6-1)*2+2=12
C5-P2-C5-P2: (12-1)*1+5=16

Hope this can help you understand~

**Comment by atonyo11** [comment]
@ycmin95 oh, I got it. Thank you very much!

**Comment by atonyo11** [comment]
@ycmin95 I understand that the delta t is the receptive field. In your paper context, does that mean the delta t is number of frames?
