### ISSUE TITLE
model or model.parameters()?

### ISSUE THREAD

**Issue by atonyo11** [ycmin95/VAC_CSLR#42]
Hi author. 
Is this line of code correct? I think it should be model.parameters()
https://github.com/ycmin95/VAC_CSLR/blob/71f3e0334fbc8cecc7ce9816ec69781068abaac0/utils/optimizer.py#L12

**Comment by ycmin95** [comment]
Thanks for pointing this out, yes, it should be model.parameters().

**Comment by atonyo11** [comment]
I got it. Thank you
