### ISSUE TITLE
Training the baseline (without VAC, SMKD)

### ISSUE THREAD

**Issue by atonyo11** [ycmin95/VAC_CSLR#44]
> The VAC result is corresponding to the setting ofloss_weights: SeqCTC: 1.0, ConvCTC: 1.0. In addition to that, the VAC+SMKD adopt the setting of model_args: share_classifier: True, weight_norm: True.

With the default setting, is it training for the baseline?

**Comment by ycmin95** [comment]
Yes, we adopt the network trained with single CTC loss as the baseline.

**Comment by atonyo11** [comment]
Thanks!
