### ISSUE TITLE
硬件配置咨询

### ISSUE THREAD

**Issue by chenzekang** [ycmin95/VAC_CSLR#8]
作者您好，请问您是用了多大的显存和内存呀？

**Comment by ycmin95** [comment]
@chenzekang 
We conduct experiments on three TITAN XP (12GB * 3) GPUs, and each end-to-end training takes about 40 hours for 80 epochs. There is no special need for RAM,  our server has 64 GB RAM. 

You can also conduct precursor experiments on framewise features (which can be extracted with the provided pretrained model under the features mode), which can accelerate the training process. However, this experiment setting can only be used for tuning the alignment module.

**Comment by chenzekang** [comment]
谢谢，非常感谢您的回复
